# Generated by Django 5.1.3 on 2025-01-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Kurs ', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['id'], 'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Talaba ', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
